on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build website
      run:
        npm install
        npm run build
    - uses: actions/checkout@v2
    
    - uses: tibor19/static-website-deploy@v1
      with:
        enabled-static-website: 'true'
        folder: 'build'
        connection-string: ${{ secrets.CONNECTION_STRING }}