# File: .github/workflows/workflow.yml


on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - uses: lauchacarro/Azure-Storage-Action@master
      with:
        enabled-static-website: 'true'
        folder: '$web'
        connection-string: ${{ secrets.CONNECTION_STRING }}











#on: [push]
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps: 
#    - uses: actions/checkout@v2
#    - uses: tibor19/static-website-deploy@v1
#      with:
#        enabled-static-website: 'true'
#        folder: '$web'
#        connection-string: ${{ secrets.CONNECTION_STRING }}